### ISSUE TITLE
change in fusionsolarurl

### ISSUE THREAD

**Issue by vdellamea** [JasperE84/PyFusionSolarDataRelay#15]
Hi, with the last system update, the fusionsolarurl (for the kiosk mode) changed to
`https://uni002eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1/station-kiosk-file?kk`

**Comment by JasperE84** [comment]
Not in my region. I had a new site installed last month (set up by a different company and on a different huawei account than my previous installation), my kiosk/api url is still the same.

I guess its different per region

**Comment by canepan** [comment]
The same happened to me, but I had to use `uni004eu5`.
Is there a way to find that URL?
It's not the one I find in the fusion website when I enable the kiosk, and documentation is a bit scarce

**Comment by JasperE84** [comment]
check out my comment here: https://github.com/JasperE84/PyFusionSolarDataRelay/issues/16#issuecomment-1937113762

**Comment by canepan** [comment]
Is there any documentation from Huaweii?
I feel like this should be made easier on their side...
