### ISSUE TITLE
pvoutputsystemid not being read correctly

### ISSUE THREAD

**Issue by cvandend** [JasperE84/PyFusionSolarDataRelay#8]
Running PyFusionSolarDataRelay 1.0.4 on a docker container on a Synology NAS.

I've set the environment variable pvoutputsystemid to what is listed at pvoutput.org. However when I start the container it says in the log:

INFO - System ID: 12345

I have also noticed that when it tries to upload to pvoutput.org 

requests.exceptions.InvalidHeader: Header part (12345) from {'X-Pvoutput-SystemId': 12345} must be of type str or bytes, not <class 'int'>

I did try to set the variable pvoutputsystemid to "XXX" but it is still read as 12345.

Any ideas?

**Comment by cvandend** [comment]
Nvm, the setup doc has a bug, it's not pvoutputsystemid, it's pvpvoutputsystemid.

**Comment by JasperE84** [comment]
Thanks!
